FROM bde2020/spark-python-template:3.1.2-hadoop3.2

ENV SPARK_APPLICATION_PYTHON_LOCATION /app/projekat1NP.py
ENV SPARK_APPLICATION_ARGS 'hdfs://namenode:9000/dir/Data' 'W01346' '2016-01-01' '2016-02-02' 2600
ENV SPARK_SUBMIT_ARGS --executor-memory 4G --executor-cores 4
