version: "3.10"

networks:
  bde:
    external: true

services:
  cassandra:
    image: cassandra:latest
    ports:
      - 9042:9042
    environment:
      - CASSANDRA_SEEDS=cassandra
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_DC=datacenter1
    networks:
      - bde
    mem_limit: 4g




  
      
